server:
  port: 8090
spring:
  application:
    name: client
  resources:
    static-locations: file:D:/yhm1.0/yihe-new-village-project-team/img/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true